package io.kuban.teamscreen.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.kuban.teamscreen.model.UserDB;

import io.kuban.teamscreen.db.UserDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDBDaoConfig;

    private final UserDBDao userDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDBDaoConfig = daoConfigMap.get(UserDBDao.class).clone();
        userDBDaoConfig.initIdentityScope(type);

        userDBDao = new UserDBDao(userDBDaoConfig, this);

        registerDao(UserDB.class, userDBDao);
    }
    
    public void clear() {
        userDBDaoConfig.getIdentityScope().clear();
    }

    public UserDBDao getUserDBDao() {
        return userDBDao;
    }

}
